name:                Prophya
version:             0.1.0.0
github:              "aidatorajiro/Prophya"
license:             MIT
author:              "nanitsukurou"
maintainer:          "kawarusosu@zoho.com"
copyright:           "2018 nakisoudayo"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/aidatorajiro/Prophya#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Prophya-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Prophya

tests:
  Prophya-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Prophya
